CUSTOM_EVENTS = {
    "Purchase": "PURCHASE",
    "Lead": "LEAD",
    "Add To Cart": "ADD_TO_CART",
    "Add Payment Info": "ADD_PAYMENT_INFO",
    "Initiate Checkout": "INITIATED_CHECKOUT",
    "Complete Registration": "COMPLETE_REGISTRATION",
    "View Content": "VIEW_CONTENT",
    "Search": "SEARCH",
    "Subscribe": "SUBSCRIBE",
    "Contact": "CONTACT",
    "Find Location": "FIND_LOCATION",
    "Schedule": "SCHEDULE",
    "Start Trial": "START_TRIAL",
    "Donate": "DONATE",
    "Customize Product": "CUSTOMIZE_PRODUCT",
    "Tutorial Completion": "TUTORIAL_COMPLETION",
    "Achievement Unlocked": "ACHIEVEMENT_UNLOCKED",
    "Level Achieved": "LEVEL_ACHIEVED",
    "Spent Credits": "SPENT_CREDITS",
    "Listing Interaction": "LISTING_INTERACTION",
    "Service Booking Request": "SERVICE_BOOKING_REQUEST",
    "Messaging Conversation Started": "MESSAGING_CONVERSATION_STARTED_7D",
    "D2 Retention": "D2_RETENTION",
    "D7 Retention": "D7_RETENTION",
    "Other": "OTHER"
}
